# Quelo Audiomaker — sequenza Calamares
# Partizionamento: modulo Quelo (disco già scelto nel wizard — niente UI partition Calamares).
---
modules-search: [ local, /usr/lib/calamares/modules ]

oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false

instances:
- id:       quelo-post
  module:   shellprocess
  config:   shellprocess-quelo.conf
- id:       quelo-riepilogo
  module:   notesqml
  config:   notesqml-quelo-riepilogo.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - users
  - notesqml@quelo-riepilogo
- exec:
  - quelo-partition-disk
  - mount
  - unpackfs
  - luksbootkeyfile
  - dpkg-unsafe-io
  - sources-media
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader-config
  - grubcfg
  - bootloader
  - packages
  - plymouthcfg
  - initramfscfg
  - initramfs
  - dpkg-unsafe-io-undo
  - sources-media-unmount
  - sources-final
  - shellprocess@quelo-post
  - umount
- show:
  - finished

branding: quelo
prompt-install: true
dont-chroot: false
